### ISSUE TITLE
ruby uri error

### ISSUE THREAD

**Issue by DarkJester** [Hood3dRob1n/Ding.rb#2]
<SNIP>
I ran the tool with a large dork list. after some time it gives an error and quits the dork in the error seems random.

Checking Bing using '/calendar.php?l=%20calendar.php?l=”' hang tight....
Checking Bing using '/calendar.php?p=%20calendar.php?p=”' hang tight....
Checking Bing using '/components/com_extended_registration/registration_detailed.inc.php?mosConfig_absolute_p%20ath= com_extended_registration' hang tight....
Checking Bing using 'components/com_forum/download.php?phpbb_root_path=%20“com_forum”' hang tight....
/usr/lib/ruby/1.9.1/uri/common.rb:176:in `split': bad URI(is not URI?): http://www.bing.com/search?q=“id=”%20& intext:”Warning: mysql_fetch_array()&qs=n&pq=“id=”%20& intext:”Warning: mysql_fetch_array()&sc=8-5&sp=-1&sk=&first=9&FORM=PORE (URI::InvalidURIError)
    from /usr/lib/ruby/1.9.1/uri/common.rb:211:in`parse'
    from /usr/lib/ruby/1.9.1/uri/common.rb:747:in `parse'
    from /usr/lib/ruby/1.9.1/uri/common.rb:994:in`URI'
    from ding2.rb:962:in `searchq'
    from ding2.rb:1368:in`block (2 levels) in <main>'
root@ikali:~/tools/Ding.rb#

**Comment by Hood3dRob1n** [comment]
You need to escape the quotes in your dork before usage at this point in time. I don't have plans for an update anytime soon so that's your only real option (or write the patch and send it to me)....
